version: "2.1"

services:

  ###############################################################
  #    Functions service
  ###############################################################

#  e-commerce-functions:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    expose:
#      - "1108"

  ###############################################################
  #    StateFun runtime
  ###############################################################

  statefun:
    image: apache/flink-statefun-playground:3.2.0-1.0
    ports:
      - "8081:8081"
      - "8090:8090"
      - "8091:8091"
#    depends_on:
#      - e-commerce-functions
    volumes:
      - ./module.yaml:/module.yaml
